# Generated by Django 5.0.3 on 2024-03-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_user_alter_advocateadmin_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='date_of_birth',
        ),
    ]
