# Generated by Django 5.0.3 on 2024-04-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_lawyerprofile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('MED', 'Medical'), ('LGL', 'Legal'), ('FIN', 'Financial'), ('HR', 'Human Resources'), ('CR', 'Criminal')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.advocateadmin'),
        ),
    ]
