# Generated by Django 5.0.3 on 2024-04-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='charity',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='session',
        ),
        migrations.RenameField(
            model_name='usersession',
            old_name='donation_amount',
            new_name='selected_advocate',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='charity',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='donation_method',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='usersession',
            name='case_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Charity',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
