# Generated by Django 5.0.3 on 2024-04-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0002_remove_donation_charity_remove_donation_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('advocate_name', models.CharField(max_length=100)),
                ('advocate_description', models.TextField()),
                ('advocate_location', models.CharField(max_length=100)),
                ('advocate_case_types', models.CharField(max_length=200)),
                ('advocate_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('case_type', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
            ],
        ),
    ]
