# Generated by Django 5.0.3 on 2024-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0006_remove_advocate_case_types_delete_casetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='case_types',
        ),
        migrations.AddField(
            model_name='advocate',
            name='case_types',
            field=models.ManyToManyField(to='ussd_app.casetype'),
        ),
    ]
