# Generated by Django 5.0.3 on 2024-04-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0007_casetype_remove_advocate_case_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
